package com.proceduralprogramming.assignments;

public class SatNav {
    // CREATE AN INTERFACE WHICH ALLOWS A FLIGHT OPERATOR
    // TO PLOT / CHART VECTORS (STRING) FOR FLIGHT NAVIGATION
    // CREATE AN AIRLINE LUFTHANSA WITH METHODS AND PARAMS
    // MAKE LUFTHANSA IMPLEMENT SATNAV INTERFACE
    // CREATE ANOTHER AIRLINE EMIRATES WITH METHODS AND PARAMS
    // MAKE EMIRATES IMPLEMENT SATNAV INTERFACE
    // SWITCH FROM LUFTHANSA TO EMIRATES, OUTPUT SHOULD CHANGE
}
