package com.proceduralprogramming.assignments;

public class StudentRecordSystem {
    // CREATE A CLASS CALLED AS SCHOOL
    // CREATE ANOTHER CLASS CALLED AS SUBJECTS
    // CREATE ANOTHER CLASS CALLED AS PERSON
    // CREATE ANOTHER CLASS CALLED AS STUDENT
    // STUDENT IS-A PERSON
    // STUDENT HAS-A SUBJECT
    // SCHOOL HAS-A STUDENT
}
